### PR TITLE
Allow an offset to be specified as a percentage

### PR DESCRIPTION
**Pull request by pads**
This may or may not help #34

I haven't been able to get the tests working for me locally so feel free to hold back on merging.  It would be good to get feedback on what I've done so far.

FYI, I'm getting the following when running karma:
```
Chrome 43.0.2357 (Linux 0.0.0): Executed 1 of 10 (1 FAILED) ERROR (5.941 secs / 5.905 secs)
INFO [watcher]: Changed file "/home/pads/development/angular-inview/test/angular-inview.spec.coffee".
Chrome 43.0.2357 (Linux 0.0.0) Directive: inView local variables should define local variables `$event`, `$inview` and `$inviewpart` FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
Chrome 43.0.2357 (Linux 0.0.0) ERROR
  Uncaught TypeError: Cannot read property 'inviewSpy' of null
```

It's hard to debug because logging and adding a breakpoint to check what `test.scope` is defined at never produces `null`.

### CODE REVIEW

**Comment by thenikso** [comment]
tests are indeed broken and I believe it could be a problem with the jasmine version.

You change seems fine tho. how is it working with a manual test?

**Comment by pads** [comment]
Thanks for the merge :) So far so good.  There might be more changes coming in future as I have noticed that the same offset does not always trigger inview at the right time when screen sizes vary.

**Comment by aendrew** [comment]
:+1: for this — I'm needing to trigger on the middle of the page and it seems I can't supply `angular.element($window).height() / 2` as a stop-gap.

**Comment by pads** [comment]
Thanks for merging this!  I forgot to update the README and version.  I'm happy to submit a follow-up pull request for this if you like.

**Comment by thenikso** [comment]
nice :) thank you @pads for helping me maintain this!

**Pull request merged**
