### PR TITLE
Remove arrow function to accomplish with ES4

### LINKED ISSUE #139: [3.0.0] Syntax Error
Great module!

I tried to upgrade my application from version 2.3.0 to 3.0.0.

Loading angular-inview in a cordova app on windows 10 triggers a javascript syntax error.
I tracked it down to be caused by the following to lines:

https://github.com/thenikso/angular-inview/blob/master/angular-inview.js#L363
https://github.com/thenikso/angular-inview/blob/master/angular-inview.js#L365

The issue disapears when I go back to version 2.3.0 of angular-inview.

### PR DESCRIPTION
**Pull request by jwhitmarsh**
Fixes #139

### CODE REVIEW

**Comment by AlexStef** [comment]
I would really enjoy having this PR merged too (besides the use of arrow function is not vital) 
:)

**Comment by 42antoine** [comment]
Same needs to, blocking on Windows 7 / IE 11.

**Comment by jwhitmarsh** [comment]
Thanks to @carauzs who actually did the work - I just created the PR!

**Comment by ideadapt** [comment]
@thenikso Can you please merge and release this PR?

**Comment by frnkst** [comment]
Please merge it

**Comment by jwhitmarsh** [comment]
@thenikso Is there any chance you could merge this? Would you like a hand maintianing this repo?

**Comment by thenikso** [comment]
hello here! I've been slacking badly with this repo. @jwhitmarsh would you like to become a contributor?

**Pull request merged**
