### PR TITLE
revert to 2.1.0, re-publish as 2.3.1

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@thenikso removing the package from "latest" doesn't really help with a semver break.

The only way to fix a semver problem is to:

revert to the old release (2.1.0)
publish a new version as a patch release to the accidentally semver breaking version (2.3.0 -> 2.3.1)
```sh
npm deprecate angular-inview@2.3.0 "accidentally pushed semver breaking version"
```
revert to the accidentally semver breaking version  (2.3.0)
publish as new semver version (3.0.0)

**Comment by graingert** [comment]
@thenikso ping?

**Comment by thenikso** [comment]
thank you a lot @graingert and sorry for the huge delay in responding to this. `v2.3.1` is now out.

on a related note, do you feel like collaborating on this repo?

**Comment by graingert** [comment]
@thenikso sorry, we switched the part of the site that used inview to react, which is able to display all the elements in one go with no jank.

**Pull request merged**
