### PR TITLE
Horizontal scroll detection added.

### PR DESCRIPTION
**Pull request by programmador**
I suppose there are no breaking changes. Even old examples are working somehow. I thought they should brake because of adding a new inView callback argument. Anyway I think the old examples will need some minor fixes.

I was alittle bit confused while fixing the offsets. Please see the modified readme.md - maybe I understood wrong how it should work.

### CODE REVIEW

**Comment by programmador** [comment]
I think tests could also be broken. I didn't try to run them

**Comment by thenikso** [comment]
reviewing this asap. @programmador would you check v2 here #107 to see if the horizontal support there is of your liking? 

Having horizontal support in v1 as well would be pretty neat tho.

**Comment by programmador** [comment]
Hmm... Looks like all the divs are initially visible while using v2. A bug?

**Comment by programmador** [comment]
I mean that I recieve inview=true in my callback even for invisible items initially, while loading the page.

**Comment by programmador** [comment]
I found that while loading the page both viewportRect and elementRect contain only zeros.
If I scroll - normal numbers occur.
So it looks like some kind of too early initialization - it starts sending events before the viewport is rendered by angularjs.

**Comment by thenikso** [comment]
that's a good catch @programmador. did you manage to go deeper in finding the bug? If so it would be great if you could open a separate PR

**Comment by programmador** [comment]
Yes, it should be separate, I think. I'll try to find out what's going on with that initialization.

**Comment by thenikso** [comment]
I'll be closing this since horizontal scroll is supported in the current v2 version. Looking forward for that initialization problem troubleshoot!

**Comment by programmador** [comment]
Right. I tried to figure out what causes the problem, but still with no success. I'm going to inspect full code of v2 to understand how it actually works. The code differs from v1 significantly and there's no sense to compare it's behaviour with v1. It looks more fancy and more "right way" but is harder to understand at first glance.

**Pull request closed without merging**
