### PR TITLE
$hasBeenInView property for element

### PR DESCRIPTION
**Pull request by aledoroshenko**
Useful when we need to check that some function already fired for this element (addresses #53). 

```
scope.someFn = function( $hasBeenInView, $inview, $inviewpart, $event ) {
    if ( $hasBeenInView ) {
        return true;
    }

    // Some code
}
```

@thenikso what do you think?

### CODE REVIEW

**Comment by aledoroshenko** [comment]
@thenikso, :shipit:

**Comment by thenikso** [comment]
Hi there, as I mentioned #53 wouldn't the problem be fixed with something like:

```
<any in-view="hasBeenInView = hasBeenInView||$inview"></any>
```

without adding code to the directive itself? What do you think?

**Comment by torch2424** [comment]
I would agree @aledoroshenko . <any in-view="hasBeenInView = hasBeenInView||$inview"></any> didn't quite work out for me.

And also, it would be a bit more apparent to the developers using this api. If you don't feel like it should be pulled, I'd suggest you at least get your suggestion in the readme, for anyone else looking for this feature.

But thank you for the awesome module by they way!

**Comment by thenikso** [comment]
if the suggested example works I don't feel this should go in. Keeping a state inside the directive is not my favorite thing. Also please check v2 to see if the new `$inviewInfo` would work for you.

**Pull request closed without merging**
